# Generated by Django 5.2 on 2025-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='entries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
