# Generated by Django 5.2 on 2025-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_rename_datetime_entries_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Journals',
        ),
    ]
